### ISSUE TITLE
misleading name

### ISSUE THREAD

**Issue by aeosynth** [qqueue/c4#2]
i thought this was a new chan written from scratch on top of html5

do you want to make a new chan written from scratch on top of html5?

**Comment by qqueue** [comment]
Nope, it's my shitty 4chanx clone that rerenders the entire page.

I'm game for writing a new board though. tinyboard is a piece of shit, but http://doushio.com/moe is pretty fucking cool.

https://github.com/lalcmellkmal/doushio

**Comment by aeosynth** [comment]
that does seem pretty fucking cool. do you have a server available? i want to develop, not get involved in legal battles over cp

**Comment by qqueue** [comment]
Unfortunately no; I'm a poor college student in the US. Heroku has free node.js / rails / other hipster framework hosting though and we could just offload image hosting to imgur or something, and let them deal with cp.

**Comment by vendethiel** [comment]
maybe u close now ?

**Comment by aeosynth** [comment]
the issue hasn't been resolved tho

**Comment by vendethiel** [comment]
But sleepover seems a better place to talk about that

**Comment by aeosynth** [comment]
it's my fault for talking about two things in one issue - html5chan is still imo a misleading name

**Comment by qqueue** [comment]
I agree that its not a great name, especially since 4chan itself is now (technically) html5.

I've always liked the name `c4`. Should I repurpose that as my userscript/extension/telepathic-HCI project, and move the dead `c4` project to a gist? The only code that's really worth keeping is the un-unicode script.

**Comment by aeosynth** [comment]
Cool coders copy continuously?

**Comment by qqueue** [comment]
I was thinking of the explosive, but a backronym is fine too.

Another option is `nanochan`, which fits with my usage of the Nichijou mythos elsewhere, but there's already a Nanoha imageboard with that name. Plus, animu-based naming is kinda...

**Comment by aeosynth** [comment]
The Chan suffix makes me think image board, not user script, so nano Chan
would not help the issue

**Comment by qqueue** [comment]
I put more thought into this, because autism:
- `c4`
  - [fairly "clean" name re: naming collisions](https://github.com/search?q=c4&ref=commandbar)
  - means nothing on its own (besides the explosive)
  - 4chan-referencing without being blatant
  - 2 characters
  - downsides
    - not directly tied to the concept of pseudonymous communication
    - 'cool coders copy continuously' is dum
- `nym`
  - as in {pseudo|ano} _nym_ ous 
  - conceptually works better than `c4` since this project's goals don't specifically depend on 4chan, the platform.
  - [clean naming on github](https://github.com/search?q=nym&type=Repositories&ref=searchresults), but not quite [globally](http://en.wikipedia.org/wiki/Nym_server)
  - one syllable is optimal
  - downsides
    - already has a non-software meaning
    - would like to avoid any association with anonymous the hacking group/trolls

**Comment by aeosynth** [comment]
Project Liger

**Comment by qqueue** [comment]
https://twitter.com/projectliger ?

**Comment by aeosynth** [comment]
Oh wow, it's already taken.

**Comment by qqueue** [comment]
I'm gonna pull the trigger on `html5chan` to `c4`. Let's see how painful github will make this.
