### ISSUE TITLE
just use json

### ISSUE THREAD

**Issue by aeosynth** [qqueue/c4#5]
instead of downloading html

**Comment by qqueue** [comment]
patches welcome.

**Comment by vendethiel** [comment]
actually making html5chan a proxy for 4chan o/

**Comment by qqueue** [comment]
> proxy 4chan

I've thought about it. Serve from my own domain, wrap 4chan API calls on the server, etc. It would take some doing though, and would be in violation of moot's ill-enforced API guidelines.

In the meantime, rerendering the page is--for all but the largest (1000+ posts) threads--working pretty okay. I still want to extract my gross backlinking implementation out of the parser code, but it's otherwise fast enough.

---

Reposting from https://github.com/MayhemYDG/4chan-x/issues/756

> @aeosynth why not just use the json api?

My DOM->object parser is already really fast, certainly faster than an HTTP request.

It's mainly my reluctance to use 4chan's HTML that requires the rerender. Mine has `<article>`s and shit, as well as eliding all of the mobile cruft. Also, since a lot of features like backlinks require massive DOM modification and reflow anyway, I just redo the entire documentElement (which has the added cool effect to completely disabling all page javascript, including the "native" extension).

> @aeosynth but you do make an http request to load the current page; you could replace the one request with the other

You're right. I've been thinking about how to do pushState single page stuff to avoid having to keep replacing vanilla 4chan for every new thread. The fact that I (and I assume pretty much everybody else) opens up threads in new tabs nullifies any advantage though. However, that also means that the ~50-500ms per page rerender overhead is usually hidden in a background tab.

Another strategy would be to run the userscript on top of the .json pages since I don't need the original DOM for anything, but that would break the url for copying. Well, I guess there's the rotating logo, and moot news too.

---

Thus, I think I'd have to move to either my own domain or a "real" firefox extension before "just use json" becomes worth it.

**Comment by vendethiel** [comment]
> opens up threads in new tabs

yes

> Another strategy would be to run the userscript on top of the .json pages

ugh.

**Comment by aeosynth** [comment]
> [json] would break the url for copying

see:

> pushState

**Comment by vendethiel** [comment]
what about new tabs ?
You want to remove all links to trigger the "page-changer" which will load from json ?

**Comment by qqueue** [comment]
Even with `replaceState`, all the links from the catalog pages would have to be rewritten to `.json`, which could then potentially be copied, and would then be broken for non-html5chan users.

I guess I could use google's technique of replacing the url on mousedown, but that's lame too.

**Comment by vendethiel** [comment]
> all the links from the catalog pages would have to be rewritten to .json

why

**Comment by qqueue** [comment]
Okay, I guess they don't if I use `window.location` redirects on all non-json pages, similar to archive redirection.

But, unless the browser runs `document-start` greasemonkey _before_ it starts loading the HTML version of the page, the speed advantage is nullified there too.

What I would need is some way to hook into the 'new tab' process of firefox before an HTTP request is sent.

**Comment by aeosynth** [comment]
so this is doable, you just have to decide if the trouble of rewriting links is worth the benefit of smaller downloads + no re-rendering

**Comment by qqueue** [comment]
Also, I'm assuming that greasemonkey will run and  let you create a DOM on top of `application/json`, which I'm pretty sure works, but I haven't tested it. I think firefox wraps the text in a DOM, so parsing would be done with `JSON.parse(document.body.textContent)`

> smaller downloads

I bet the difference here is really minimal, considering the HTML is gzipped anyway.

> no re-rendering

You know, I'm actually not so sure about the difference now. Since I replace `documentElement` at `document-start`, firefox never attempts to render the original DOM (doesn't even pull the scripts or CSS), it only parses the HTML for `DOMContentLoaded`. So it's more of a re-parse rather than a re-render. I don't have metrics around vanilla 4chan or 4chan-X, but the true overhead of html5chan compared to them might turn out to be pretty small.

Back when I was using jQuery and handlebars there would have been more to discuss, but right now, I think the page load is actually fairly tight.

**Comment by aeosynth** [comment]
extracting data at least is definitely easier with json than with html -> dom

**Comment by qqueue** [comment]
True enough. An [imageboard microdata schema like tinyboard used to have](https://github.com/savetheinternet/Tinyboard/blob/c5a961a6a52af8a0d6c0085668fe71d9d9de3a9c/templates/post_reply.html) would make parsing easier, but moot will never do that.

**Comment by aeosynth** [comment]
i'm closing old issues

**Comment by vendethiel** [comment]
guess I should do the same at some point :P

**Comment by aeosynth** [comment]
it's awkward because some of the projects are still active, even if they have a huge backlog
