### ISSUE TITLE
Use package.json devDependancies

### ISSUE THREAD

**Issue by fulmicoton** [qqueue/c4#8]
Npm offers a devDependancies options that let's you define the stuff you need to install to build.

Those will be install in node_modules when running npm install .
You can also define a build script shortcut. 

---

My bad. I need some sleep.

**Comment by qqueue** [comment]
Er, I'm not sure if you meant to open a bug here, but in any case, I think I addressed the issue. Since htmlchan isn't a node library, I'm using `package.json` purely for easy dependency management, so the `devDepedency` behavior isn't really relevant to me outside of semantics. 

But, I did switch to using npm's `run-script` to avoid needing to install `coke` globally, so the installation instructions are less dumb now.

**Comment by fulmicoton** [comment]
Thank you. And yes I agree, my message about devDependancies was plain stupid. Sorry for that,
